name: todo-prod
services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: 4000
      NODE_ENV: production
    networks:
      - prod-network
    command: npx prisma migrate deploy
    restart: on-failure

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      SERVER_PORT: 4000
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - prod-network
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prod-network:
    name: prod-network
